language: rust
rust: stable

cache: cargo

env: MDBOOK=0.1 GHP_UPLOAD=0.3

install:
- cargo install --version $MDBOOK mdbook
- cargo install --version $GHP_UPLOAD cargo-ghp-upload

script: mdbook build && cargo ghp-upload --directory book -vv
